DeepRobSite/DeepRobSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('robweb.urls')),
]

DeepRobSite/robweb/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'robweb'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^img_upload', views.img_upload, name='img_upload'),
    url(r'^gallery', views.gallery, name='gallery'),
    url(r'^img/(?P<img_name>.+)/$', views.detail, name='detail'),
    url(r'^result/(?P<img_name>.+)/$', views.result, name='result'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DeepRobSite/robweb/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class TfImage(models.Model):
    img = models.ImageField(upload_to='tf_images', blank=False, null=True)
    name = models.CharField(max_length=200, blank=True, default='')
    result = models.TextField(default='', blank=True, null=True)
    upload_date = models.DateTimeField(blank=True, null=False)

    def __str__(self):
        return self.img.name

DeepRobSite/robweb/forms.py
from django import forms
from .models import TfImage


class ImageForm(forms.ModelForm):

    class Meta:
        model = TfImage
        fields = ('img',)

DeepRobSite/robweb/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import JsonResponse
from .forms import ImageForm
from .models import TfImage
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.core.files.images import ImageFile


def index(request):
    return render(request, 'robweb/index.html')


def detail(request, img_name):
    tf_image = get_list_or_404(TfImage, name=img_name)[0]
    context = {
        'img': tf_image
    }
    return render(request, 'robweb/detail.html', context)


def result(request, img_name):
    tf_image = get_list_or_404(TfImage, name=img_name)[0]
    response = {
        'img_name': img_name,
        'result': tf_image.result
    }
    return JsonResponse(response)


@csrf_exempt
def img_upload(request):
    if request.method == 'POST':
        img_form = ImageForm(request.POST, request.FILES)
        if img_form.is_valid():
            if 'img' in request.FILES:
                TfImage.objects.create(
                    name=request.FILES['img'].name,
                    img=request.FILES['img'],
                    upload_date=timezone.datetime.now()
                )
        else:
            print(img_form.errors)

    else:
        img_form = ImageForm()
        context = {
            'img_form': img_form,
        }
        return render(request, 'robweb/img_upload.html', context)

    return render(request, 'robweb/img_res.html')


def gallery(request):
    imgs = TfImage.objects.order_by('-upload_date')
    paginator = Paginator(imgs, 9)  # Show 9 words per page

    page = request.GET.get('page')
    try:
        imgs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        imgs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        imgs = paginator.page(paginator.num_pages)

    return render(request, 'robweb/gallery.html', {'imgs': imgs})

DeepRobSite/robweb/templates/robweb/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>DeepRobotics</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'robweb/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
      <link href="{% static 'robweb/css/3-col-portfolio.css" rel="stylesheet">
    <link href="{% static 'robweb/starter-template.css' %}" rel="stylesheet">

  </head>

    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'robweb:index' %}">DeepRobotics</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'robweb:gallery' %}">Gallery</a>
                        </li>
                        <li>
                            <a href="{% url 'robweb:img_upload' %}">Image Upload</a>
                        </li>
                        <li>
                            <a href="/admin">Admin</a>
                        </li>
                        <li>
                            <a href="https://github.com/MediffRobotics/DeepRobotics">GitHub</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block body_block %}
            This is body_block's default content.
        {% endblock %}

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'robweb/js/jquey.js' %}js/jquery.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="{% static 'robweb/dist/js/bootstrap.min.js' %}"></script>


    </body>

</html>

DeepRobSite/robweb/templates/robweb/detail.html
{% extends 'robweb/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Upload Image
{% endblock %}

{% block body_block %}

    <div class="container">

      <div class="starter-template">
        <h1>{{img.name}}</h1>
        <p class="lead" id="result">{{img.result}}</p>
      </div>

    </div>

{% endblock %}

DeepRobSite/robweb/templates/robweb/gallery.html
{% extends 'robweb/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Gallery
{% endblock %}

{% block body_block %}


<!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Gallery
                    <small>Source Images</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        {% if imgs %}

        <!-- Projects Row -->
        <div class="row">
            {% for img in imgs %}
            {% if forloop.counter  < 4 %}
            <div class="col-md-4 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="../media/{{img.img }}" alt="">
                </a>
                <h3>
                    <a href="{% url 'robweb:detail' img.name %}">{{img.name}}</a>
                </h3>
                <p>{{img.upload_date}}, {{img.result}}</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>

        <!-- Row 2 -->
        <div class="row">
            {% for img in imgs %}
            {% if forloop.counter  > 3 and forloop.counter < 7 %}
            <div class="col-md-4 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="../media/{{img.img }}" alt="">
                </a>
                <h3>
                    <a href="{% url 'robweb:detail' img.name %}">{{img.name}}</a>
                </h3>
                <p>{{img.upload_date}}, {{img.result}}</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>

        <!-- Row 3 -->
        <div class="row">
            {% for img in imgs %}
            {% if forloop.counter  > 6%}
            <div class="col-md-4 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="../media/{{img.img }}" alt="">
                </a>
                <h3>
                    <a href="{% url 'robweb:detail' img.name %}">{{img.name}}</a>
                </h3>
                <p>{{img.upload_date}}, {{img.result}}</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <!-- /.row -->


        <hr>

        <!-- Pagination -->
        {% if imgs.paginator.num_pages > 1 %}
        <hr/>
        <ul class="pagination">
            {% if imgs.number > 1 %}
            <li class="paginate_button " aria-controls="dataTables-example" tabindex="0">
                <a href="?page=1">1 <<</a>
            </li>
            {% endif %}
            {% if imgs.has_previous %}
            <li class="paginate_button previous" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_previous">
                <a href="?page={{ imgs.previous_page_number }}"><</a>
            </li>
            {% endif %}
            <li class="paginate_button active" aria-controls="dataTables-example" tabindex="0">
                <a href="#">{{imgs.number}}</a>
            </li>
            {% if imgs.has_next %}
            <li class="paginate_button next" aria-controls="dataTables-example" tabindex="0" id="dataTables-example_next">
                <a href="?page={{ imgs.next_page_number }}"> ></a>
            </li>
            {% endif %}
            {% if imgs.number < imgs.paginator.num_pages %}
            <li class="paginate_button " aria-controls="dataTables-example" tabindex="0">
                <a href="?page={{ imgs.paginator.num_pages }}">>> {{ imgs.paginator.num_pages }}</a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
        <!-- /.row -->
        
        
        {% else %}
        <p>No images are available.</p>
        {% endif %}


    </div>
    <!-- /.container -->


{% endblock %}

DeepRobSite/robweb/templates/robweb/img_res.html
{% extends 'robweb/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Upload Result
{% endblock %}

{% block body_block %}

    <div class="container">

      <div class="starter-template">
          <p class="lead">Image Uploaded<br>
            </p>
          <a href="{% url 'robweb:gallery' %}">View Uploaded Image</a>
          <a href="{% url 'robweb:img_upload' %}">Upload Again</a>
      </div>

    </div><!-- /.container -->

{% endblock %}

DeepRobSite/robweb/templates/robweb/img_upload.html
{% extends 'robweb/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}

    <div class="container">
        <div class="starter-template">
            <div class="panel panel-default">
            <div class="panel-heading">
                Image Upload
            </div>
            <div class="panel-body">
                <form role="form" id="img_form" method="post" action="{% url 'robweb:img_upload' %}"
                enctype="multipart/form-data">
                    <fieldset>
                        {% csrf_token %}
                        {{ img_form.img }}
                        <input type="submit" name="submit" value="Upload" class="btn  btn-default "/>
                    </fieldset>
                </form>
            </div>
        </div>
        </div>
    </div>

{% endblock %}

DeepRobSite/robweb/templates/robweb/index.html
{% extends 'robweb/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Upload Image
{% endblock %}

{% block body_block %}

    <div class="container">

      <div class="starter-template">
        <h1>DeepRobotics</h1>
        <p class="lead">Welcome to our machine learning Project.<br>
            </p>
      </div>

    </div>

{% endblock %}